# Generated by Django 3.0.4 on 2020-05-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smm_backend', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uder_id',
            new_name='user_id',
        ),
    ]
