# Generated by Django 3.0.4 on 2020-05-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm_backend', '0003_auto_20200508_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('vk', models.BooleanField()),
                ('date_post', models.DateTimeField()),
                ('group_id', models.CharField(max_length=50)),
            ],
        ),
    ]
